from enum import Enum

class ExcelColumnMap(Enum):
    emp_id = "Emp ID"
    emp_name = "Emp Name"
    grade = "Grade"
    department = "Department"
    client = "Client"
    project = "Project"
    project_code = "Project Code"
    account_manager = "Account Manager"
    practice_lead = "Practice Lead/ Head"
    delivery_manager = "Delivery/ Project Manager"
    duration_month = "Duration Month"
    payroll_month = "Payroll Month"
    billability_status = "Billability Status"
    practice_remarks = "Practice Remarks"
    rmg_comments = "RMG Comments"
    shift_a_days = "Shift A\n(09 PM to 06 AM)\nINR 500"
    shift_b_days = "Shift B\n(04 PM to 01 AM)\nINR 350"
    shift_c_days = "Shift C\n(06 AM to 03 PM)\nINR 100"
    prime_days = "Prime\n(12 AM to 09 AM)\nINR 700"
    total_days = "TOTAL DAYS"